[package]
name = "sc2mpz"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.10", features = ["derive"] }
phf = { version = "0.10.1", features = ["macros"] }
rmp-serde = "1.1.0"
serde = { version = "1.0.136", features = ["derive", "rc"] }
strum = "0.24.0"
strum_macros = "0.24.0"
gzp = "0.9.5"
log = "0.4.16"
simplelog = "0.12.0"
