[package]
name = "sc2mpz"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"
clap = { version = "3.2.15", features = ["derive"] }
phf = { version = "0.11.0", features = ["macros"] }
rmp-serde = "1.1.0"
serde = { version = "1.0.140", features = ["derive", "rc"] }
strum = "0.24.1"
strum_macros = "0.24.2"
gzp = "0.10.1"
log = "0.4.17"
simplelog = "0.12.0"
