name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  rust-clippy:
    runs-on: 'ubuntu-18.04'

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Install Build Dependencies
        run: cargo install clippy-sarif sarif-fmt
      - name: Check
        run: |
          cargo clippy --all-targets --message-format json -- -D warnings | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
